[[plugins]]
	package = "@netlify/plugin-sitemap"
        [plugins.inputs]
        trailingSlash = true

[build.environment]
  NODE_VERSION = "18"
  NODE_OPTIONS = "--openssl-legacy-provider"
  AWS_LAMBDA_JS_RUNTIME = "nodejs18.x"